### ISSUE TITLE
Register action fails for new user

### ISSUE THREAD

**Issue by rajeshg** [s-petr/longhabit#1]
Steps to reproduce:
1. Clone git repo at https://github.com/s-petr/longhabit/
2. bun install
3. bun run build
4. Create admin user with ./longhabit superuser upsert EMAIL PASS
5. Start the app with ./longhabit serve
6. Visit http://127.0.0.1:8090/register and try to register.
7. Expected: New user gets created without error.  Actual: New user gets created in pocketbase, but users sees an error "Failed to create record" as the Pocketbase API call to http://127.0.0.1:8090/api/collections/users/records return a HTTP 400 with {"data":{},"message":"Failed to create record.","status":400}

**Comment by s-petr** [comment]
@rajeshg seems like you have an issue with file permissions. Did the folder /db get created in the project directory? If yes, does it contain the database files (data.db and auxiliary.db)? Do you have permissions to read and write to this folder with the account you are logged in as?

I tried to recreate the steps you made using a fresh git clone but I had no issues. But I'm using Linux so if you're on a different OS it may vary.

**Comment by rajeshg** [comment]
Hmm. I am on Linux (but using Windows WSL2). I do have permissions and the db folder did get created in the project directory. 

```
ubuntu@localhost:~/sde/workspace/longhabit$ ls db/
auxiliary.db  auxiliary.db-shm  auxiliary.db-wal  data.db  data.db-shm  data.db-wal  storage
```
