### ISSUE TITLE
Plausible setup instructions

### ISSUE THREAD

**Issue by osaxon** [s-petr/longhabit#2]
Hi there! first of all thanks for sharing this template, it looks great and I'm planning on using it for a new project.
I noticed an error in the network tab that I traced back to plausible. I've created an account with plausible and followed the instructions they provide i.e. adding the script tag to the head component, but I can't seem to get it working.

I was wondering if you could clarify how you have it set up? This is the error I'm getting:

![image](https://github.com/user-attachments/assets/527a60dc-0dd6-4585-8790-0ac3c4ca436b)

**Comment by s-petr** [comment]
Hi @osaxon,

Are you self-hosting Plausible Analytics on your own domain "https://dark-city.webjenga.com"? If you're using the managed version of Plausible you should be sending requests to "https://plausible.io".

In my project I'm self-hosting Plausible Analytics Community Edition on my own server. I'm connecting to it using the NPM package [plausible-tracker](https://www.npmjs.com/package/plausible-tracker). It provides the same functionality as the script tags. But it's a cleaner integration with React if you want to use some of the more advanced features like custom event tracking.

It should work out of the box if you set environment variables correctly. This can be done in multiple places:

In Docker Compose file ([docker-compose.yml](/s-petr/longhabit/blob/main/docker-compose.yml#L6-8)) - change these lines
``` yaml
      args:
        - COOLIFY_FQDN={{put the domain of your site here}}
        - PLAUSIBLE_API_HOST={{put the domain of Plausible here}}
```

Or in the [Dockerfile](/s-petr/longhabit/blob/main/Dockerfile#L10) - change this line
``` yaml
VITE_DOMAIN={{put the domain of your site here}}\nVITE_PLAUSIBLE_API_HOST={{put the domain of Plausible here}}
```

Or add a .env file with these lines to the root directory of the project
```
VITE_DOMAIN={{put the domain of your site here}}
VITE_PLAUSIBLE_API_HOST={{put the domain of Plausible here}}
```

Or in [plausible-context.tsx](/s-petr/longhabit/blob/main/frontend/src/context/plausible-context.tsx#L6-10) change these lines:
``` typescript
const plausible = Plausible({
  domain: /* {{put the domain of your site here}} */,
  apiHost: /* {{put the domain of Plausible here or delete this if you're using the managed version (defaults to 'https://plausible.io' }} */,
  trackLocalhost: true
})
```

When using the NPM package the project exposes the trackEvent method using the React Context API usePlausible hook that you can use to add custom events. There are useful examples in the [use-auth.ts](/s-petr/longhabit/blob/main/frontend/src/hooks/use-auth.ts#L56-67) file. For example there's a custom event when someone logs in using Google:
``` typescript
const { trackEvent } = usePlausible()
//imports the trackEvent method using React Context API

  const loginWithGoogle = async () => {
    try {
      const authResult = await loginWithGoogleApi()
      // after the user successfully logs in using Google, send a custom event to Plausible
      trackEvent('login', { props: { method: 'google' } })
      subscribeToUserChanges(authResult.record.id, subscribeUserChangeCallback)
      queryClient.invalidateQueries({ queryKey: ['user'] })
      router.invalidate()
      router.navigate({ to: '/tasks' })
    } catch (error) {
      errorToast('Could not log in', error)
    }
  }

```
You can use the same procedure to add custom events that are relevant for your project.

If you don't want to use the [plausible-tracker](https://www.npmjs.com/package/plausible-tracker) NPM package you can uninstall it, delete [plausible-context.tsx](/s-petr/longhabit/blob/main/frontend/src/context/plausible-context.tsx), delete `<PlausibleProvider>` from [root.tsx](/s-petr/longhabit/blob/main/frontend/src/root.tsx#L12). Then delete any references to the usePlausible hook and the trackEvent method.

This will completely remove Plausible Analytics from the project. If you don't need web analytics you can stop here and continue working on your project. Or you can add Plausible using the simpler method by adding the `<script>` tag to index.html. This is the default way that is recommended in the Plausible Analytics docs. Or you can switch to a different web analytics provider.

Hope that helps.

**Comment by osaxon** [comment]
thanks, that explains it
